---
# tasks file for role "booked"

- include: "setup-{{ ansible_os_family }}.yml"

- name: bookedscheduler | remove existing installation
  file: path='{{ booked_install_dir }}' state=absent

- name: bookedscheduler | create install directory
  file: path="{{ booked_install_dir }}" state=directory owner={{ booked_apache_user }} group={{ booked_apache_user }} mode=0700
- name: bookedscheduler | create log directory
  file: path="{{ booked_log_dir }}" state=directory owner={{ booked_apache_user }} group={{ booked_apache_user }} mode=0775

- block:
  - name: bookedscheduler | unpack local source archive
    unarchive: src="{{ booked_source_local_archive }}" dest=/tmp
  - name: bookedscheduler | move source to installation directory
    shell: mv /tmp/booked/* "{{ booked_install_dir }}"
  when: booked_source == "local_archive"

- name: bookedscheduler | copy source from local directory
  synchronize: src="{{ booked_source_local_dir }}" dest="{{ booked_install_dir }}"
  when: booked_source == "local_directory"

- block:
  - name: bookedscheduler | check if known_hosts_github exists
    stat: path="{{ booked_source_git_known_hosts_file }}"
    register: known_hosts_github
  # https://gist.github.com/maxim/871e611d4bc02c633c67
  - name: bookedscheduler | ensure github.com is a known host
    lineinfile:
      dest: "{{ booked_source_git_known_hosts_file }}"
      create: yes
      state: present
      line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
      regexp: "^github\\.com"
    when: not known_hosts_github.stat.exists
  - name: bookedscheduler | set permissions on /root/.ssh/
    file: path=/root/.ssh mode=0700
  - name: bookedscheduler | set permissions on known_hosts_github
    file: path="{{ booked_source_git_known_hosts_file }}" mode=0600
  - name: bookedscheduler | get source from Git
    git: repo="{{ booked_source_git_repo }}" version="{{ booked_source_git_version }}" dest="{{ booked_install_dir }}" accept_hostkey=yes ssh_opts="-o UserKnownHostsFile={{ booked_source_git_known_hosts_file }}"
  when: booked_source == "git"


- name: bookedscheduler | template Booked config file
  template: src=config.php dest="{{ booked_install_dir }}/config/config.php"

- name: bookedscheduler | template Booked log config file
  template: src=log4php.config.xml dest="{{ booked_install_dir }}/config/log4php.config.xml"

- name: bookedscheduler | create .htaccess file
  shell: echo "DirectoryIndex index.php" > "{{ booked_install_dir }}/.htaccess"
  args:
    creates: "{{ booked_install_dir }}/.htaccess"

- name: bookedscheduler | fix ownership of installation directory
  file: path="{{ booked_install_dir }}" recurse=yes owner={{ booked_apache_user }} group={{ booked_apache_user }}
