---
# tasks file for role "booked"

# Setup/install tasks.
- include: setup-CentOS.yml
  when: ansible_distribution == 'CentOS'

- include: setup-RedHat.yml
  when: ansible_distribution == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'


- name: check if this first install
  stat: path=/var/www/html/config/config.php
  register: previously_provisioned

- name: remove default /var/www/html/index.html
  file: path=/var/www/html/index.html state=absent

- name: create directories
  file: path={{ item }} state=directory owner={{ apache_user }} group={{ apache_user }}
  with_items:
    - "{{ booked_log_dir }}"


# unpack source and move to document root
- unarchive: src=booked-2.5.13.zip dest=/tmp
  when: previously_provisioned.stat.exists == False
- shell: mv /tmp/booked/* /var/www/html
  when: previously_provisioned.stat.exists == False

- name: template Booked config file
  template: src=config.php dest=/var/www/html/config/config.php

- debug: var=mysql_user_password

- name: template Booked log config file
  template: src=log4php.config.xml dest=/var/www/html/config/log4php.config.xml

- name: create .htaccess file
  shell: echo "DirectoryIndex index.php" > /var/www/html/.htaccess
  args:
    creates: /var/www/html/.htaccess

- name: fix ownership of /var/www/html
  file: path=/var/www/html recurse=yes owner={{ apache_user }} group={{ apache_user }}

#- name: restart apache2
#  service: name=apache2 state=restarted
#  when: not build_docker_image
