---
# tasks file for role "booked"

# Setup/install tasks.
- include: setup-CentOS.yml
  when: ansible_distribution == 'CentOS'

- include: setup-RedHat.yml
  when: ansible_distribution == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'


- name: remove existing installation
  file: path='{{ booked_install_dir }}' state=absent

- name: create directories
  file: path={{ item }} state=directory owner={{ apache_user }} group={{ apache_user }}
  with_items:
    - "{{ booked_install_dir }}"
    - "{{ booked_log_dir }}"

- name: unpack source archive
  unarchive: src=booked-2.5.19.zip dest=/tmp
- name: move source to installation directory
  shell: mv /tmp/booked/* "{{ booked_install_dir }}"

- name: template Booked config file
  template: src=config.php dest="{{ booked_install_dir }}/config/config.php"

- name: template Booked log config file
  template: src=log4php.config.xml dest="{{ booked_install_dir }}/config/log4php.config.xml"

- name: create .htaccess file
  shell: echo "DirectoryIndex index.php" > "{{ booked_install_dir }}/.htaccess"
  args:
    creates: "{{ booked_install_dir }}/.htaccess"

- name: fix ownership of installation directory
  file: path="{{ booked_install_dir }}" recurse=yes owner={{ apache_user }} group={{ apache_user }}
